FROM public.ecr.aws/lambda/python:3.13

# Install poetry
RUN pip install "poetry"

# Task dir & copy
WORKDIR ${LAMBDA_TASK_ROOT}
COPY . ${LAMBDA_TASK_ROOT}/

# Project initialization:
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root

# Set the CMD to your handler 
CMD [ "modelled_needs.index.LambdaHandler" ]